#!/usr/bin/env node
// gen-tokens.mjs — convert the Figma variables export into Flutter Dart token files.
// Source: figma-variables-export.json  →  ../lib/theme/tokens/*.dart
// Run:  node gen-tokens.mjs
//
// Generated, never hand-edited. Re-run after re-exporting variables from Figma.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const SRC = join(here, "figma-variables-export.json")
const OUT = join(here, "..", "lib", "theme", "tokens")
mkdirSync(OUT, { recursive: true })

const data = JSON.parse(readFileSync(SRC, "utf8"))
const byId = new Map(data.variables.map((v) => [v.id, v]))
const colName = new Map(data.collections.map((c) => [c.id, c.name]))

/* ----------------------------------------------------------------- helpers */

const DART_KEYWORDS = new Set([
  "default", "class", "const", "new", "void", "var", "final", "in", "is",
  "this", "true", "false", "null", "switch", "case", "if", "else", "for",
])

function ident(name, { dropFirst } = {}) {
  let parts = name.split("/").map((p) => p.trim()).filter(Boolean)
  if (dropFirst && parts[0] === dropFirst) parts = parts.slice(1)
  const words = parts.flatMap((p) => p.split(/[^a-zA-Z0-9]+/).filter(Boolean))
  let id = words
    .map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1)))
    .join("")
  if (/^\d/.test(id)) id = "n" + id
  if (DART_KEYWORDS.has(id)) id += "Color"
  return id
}

const ch = (v) => Math.round(v * 255).toString(16).padStart(2, "0").toUpperCase()
function argb(c) {
  const a = c.a === undefined ? 1 : c.a
  return `0x${ch(a)}${ch(c.r)}${ch(c.g)}${ch(c.b)}`
}

function resolveColor(value) {
  let v = value
  let guard = 0
  while (v && v.type === "VARIABLE_ALIAS" && guard++ < 12) {
    const t = byId.get(v.id)
    if (!t) return null
    const first = Object.values(t.valuesByMode)[0]
    v = first?.value
  }
  return v && "r" in v ? v : null
}

function modeValue(v, modeName) {
  const m = v.valuesByMode[modeName]
  return m ? m.value : null
}

const header = (title) =>
  `// GENERATED by figma-rest-api/gen-tokens.mjs — do not edit by hand.\n` +
  `// Source: Figma variables export. ${title}\n\nimport 'package:flutter/material.dart';\n\n`

/* --------------------------------------------------------- 1. primitives */

const primitives = data.variables.filter(
  (v) => colName.get(v.collectionId) === "Primitives" && v.resolvedType === "COLOR",
)
{
  let out = header("Primitive color palette — raw values, no light/dark.")
  out += "/// Raw palette primitives. Prefer [AppColors] semantic tokens in UI;\n"
  out += "/// use these only when a semantic token does not exist.\n"
  out += "abstract final class Palette {\n"
  for (const v of primitives) {
    const c = resolveColor(Object.values(v.valuesByMode)[0]?.value)
    if (!c) continue
    out += `  static const Color ${ident(v.name)} = Color(${argb(c)});\n`
  }
  out += "}\n"
  writeFileSync(join(OUT, "palette.dart"), out)
  console.log("✓ palette.dart  (" + primitives.length + " colors)")
}

/* --------------------------------------- 2. semantic colors (ThemeExtension) */

const semCol = data.collections.find((c) => c.name === "Semantic")
const lightMode = semCol.modes.find((m) => /light/i.test(m.name)).name
const darkMode = semCol.modes.find((m) => /dark/i.test(m.name)).name
// canonical, namespaced tokens only (skip legacy flat duplicates)
const semantics = data.variables.filter(
  (v) =>
    v.collectionId === semCol.id &&
    v.resolvedType === "COLOR" &&
    v.name.startsWith("color/"),
)
const fields = semantics.map((v) => {
  const id = ident(v.name, { dropFirst: "color" })
  const light = resolveColor(modeValue(v, lightMode))
  let dark = resolveColor(modeValue(v, darkMode))
  if (!dark) dark = light
  return { id, light, dark, name: v.name, desc: v.description }
})

{
  let out = header("Semantic colors with light & dark modes (ThemeExtension).")
  out += "@immutable\nclass AppColors extends ThemeExtension<AppColors> {\n"
  for (const f of fields) {
    if (f.desc) out += `  /// ${f.desc.replace(/\s+/g, " ").trim()}\n`
    out += `  final Color ${f.id};\n`
  }
  out += "\n  const AppColors({\n"
  for (const f of fields) out += `    required this.${f.id},\n`
  out += "  });\n\n"

  // light
  out += "  static const AppColors light = AppColors(\n"
  for (const f of fields) out += `    ${f.id}: Color(${argb(f.light)}),\n`
  out += "  );\n\n"
  // dark
  out += "  static const AppColors dark = AppColors(\n"
  for (const f of fields) out += `    ${f.id}: Color(${argb(f.dark)}),\n`
  out += "  );\n\n"

  // copyWith
  out += "  @override\n  AppColors copyWith({\n"
  for (const f of fields) out += `    Color? ${f.id},\n`
  out += "  }) => AppColors(\n"
  for (const f of fields) out += `    ${f.id}: ${f.id} ?? this.${f.id},\n`
  out += "  );\n\n"

  // lerp
  out += "  @override\n  AppColors lerp(ThemeExtension<AppColors>? other, double t) {\n"
  out += "    if (other is! AppColors) return this;\n    return AppColors(\n"
  for (const f of fields)
    out += `      ${f.id}: Color.lerp(${f.id}, other.${f.id}, t)!,\n`
  out += "    );\n  }\n}\n"

  writeFileSync(join(OUT, "app_colors.dart"), out)
  console.log("✓ app_colors.dart  (" + fields.length + " semantic tokens × light/dark)")
}

/* ----------------------------------------------------- 3. typography tokens */

const typo = data.variables.filter((v) => v.collectionId ===
  data.collections.find((c) => c.name === "Typography").id)
const T = {}
for (const v of typo) {
  const val = Object.values(v.valuesByMode)[0]?.value
  T[v.name] = typeof val === "string" ? val.replace(/^"|"$/g, "") : val
}
const weightEnum = (w) => `FontWeight.w${w}`
function style(role) {
  const fam = T[`font/${role}/family`]
  const wt = T[`font/${role}/weight`]
  return { fam, wt }
}
{
  let out = header("Typography — Prompt (heading/label) & Inter (body/caption).")
  out += "/// Font families must be declared in pubspec.yaml (fonts: section)\n"
  out += "/// or provided via google_fonts. Names: 'Prompt', 'Inter'.\n"
  out += "abstract final class AppTypography {\n"
  out += `  static const String headingFamily = '${T["font/heading/family"]}';\n`
  out += `  static const String bodyFamily = '${T["font/body/family"]}';\n`
  out += `  static const String labelFamily = '${T["font/label/family"]}';\n`
  out += `  static const String captionFamily = '${T["font/caption/family"]}';\n\n`

  const defs = [
    ["headingLg", "heading", T["font/heading/size/lg"], T["font/heading/line-height/lg"]],
    ["headingMd", "heading", T["font/heading/size/md"], T["font/heading/line-height/md"]],
    ["headingSm", "heading", T["font/heading/size/sm"], T["font/heading/line-height/sm"]],
    ["bodyMd", "body", T["font/body/size/md"], T["font/body/line-height/md"]],
    ["bodySm", "body", T["font/body/size/sm"], T["font/body/line-height/sm"]],
    ["labelLg", "label", T["font/label/size/lg"], T["font/label/line-height/lg"]],
    ["labelMd", "label", T["font/label/size/md"], T["font/label/line-height/md"]],
    ["labelSm", "label", T["font/label/size/sm"], T["font/label/line-height/sm"]],
    ["captionMd", "caption", T["font/caption/size/md"], T["font/caption/line-height/md"]],
    ["captionSm", "caption", T["font/caption/size/sm"], T["font/caption/line-height/sm"]],
  ]
  for (const [id, role, size, lh] of defs) {
    const s = style(role)
    out += `  static const TextStyle ${id} = TextStyle(\n`
    out += `    fontFamily: ${role}Family,\n`
    // Inter has no Thai glyphs — fall back to Prompt for Thai text.
    if (s.fam !== "Prompt") {
      out += `    fontFamilyFallback: <String>['Prompt'],\n`
    }
    out += `    fontSize: ${size},\n`
    out += `    height: ${lh} / ${size},\n`
    out += `    fontWeight: ${weightEnum(s.wt)},\n`
    out += `  );\n`
  }
  out += "}\n"
  writeFileSync(join(OUT, "app_typography.dart"), out)
  console.log("✓ app_typography.dart  (" + defs.length + " text styles)")
}

/* --------------------------------------------------------- 4. border radius */

const radii = data.variables.filter(
  (v) => colName.get(v.collectionId) === "Border Radius",
)
{
  let out =
    "// GENERATED by figma-rest-api/gen-tokens.mjs — do not edit by hand.\n" +
    "// Source: Figma variables export. Border radius scale.\n\n"
  out += "abstract final class AppRadius {\n"
  for (const v of radii) {
    const val = Object.values(v.valuesByMode)[0]?.value
    out += `  static const double ${ident(v.name, { dropFirst: "border-radius" })} = ${val};\n`
  }
  out += "}\n"
  writeFileSync(join(OUT, "app_radius.dart"), out)
  console.log("✓ app_radius.dart  (" + radii.length + " radii)")
}

console.log("\nDone → " + OUT)
